version: 2.1

jobs:
  cypress-tests:
    docker:
      - image: cypress/browsers:latest

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run Cypress tests
          command: npx cypress run

      - run:
          name: Generate Allure report
          command: npm run allure:report

      - store_artifacts:
          path: cypress/videos
          destination: videos

      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots

      - store_artifacts:
          path: allure-report
          destination: allure-report

workflows:
  build-and-test:
    jobs:
      - cypress-tests