version: 2.1

jobs:
  node-job:
    docker:
      - image: cypress/browsers:node-20.17.0-chrome-124.0.6367.207-1-ff-125.0.3-edge-124.0.2478.51-1

    steps:
      - checkout

      - run:
          name: Install npm packages
          command: npm ci

      - run:
          name: Install Allure
          command: |
            curl -sSL https://github.com/allure-framework/allure2/releases/download/2.19.0/allure-2.19.0.zip -o allure.zip
            unzip allure.zip -d /opt/allure
            ln -s /opt/allure/allure-2.19.0/bin/allure /usr/bin/allure

      - run:
          name: Run tests
          command: npx cypress run

      - run:
          name: Generate report
          command: npm run allure:report

      - store_artifacts:
          path: allure-report
          destination: CypressReport

workflows:
  build-and-test:
    jobs:
      - node-job